name: Integration Test

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
    Tests:
        name: Integration test
        runs-on: ubuntu-latest

        env:
            DB_DATABASE: csye_6225
            DB_USER: root
            DB_PASSWORD: root
        
        strategy:
            matrix:
                node-version: [21.x]


        steps:
            - name: Set up MySQL
              run: |
                sudo /etc/init.d/mysql start
                mysql -e 'CREATE DATABASE ${{ env.DATABASE_NAME }};' -u${{ env.DATABASE_USER }} -p${{ env.DATABASE_PASSWORD }}

            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
            - run: npm ci
            - run: npm install sequelize
            - run: npm install mysql2
            - run: npm run build --if-present
            - run: npm test


